[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.95"
# gettext-rs = "0.7.0"
# gettext-sys = "0.21.3"
libc = "0.2.153"
ncurses = "6.0.0"
rand = "0.8.5"
